2024-10-02 08:06:26,587 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-02 08:06:26,587 - INFO - [33mPress CTRL+C to quit[0m
2024-10-02 08:07:05,415 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-02 08:07:05,415 - INFO - [33mPress CTRL+C to quit[0m
2024-10-02 08:11:45,911 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-02 08:11:45,912 - INFO - [33mPress CTRL+C to quit[0m
2024-10-02 08:16:35,600 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\main.py", line 90, in root
    return render_template('main.html', player_board=player1_board)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\templates\main.html", line 15, in top-level template code
    grid-template-columns: repeat({{player_board|length}}, 1fr);
    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-10-02 08:16:35,603 - INFO - 127.0.0.1 - - [02/Oct/2024 08:16:35] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-02 08:16:35,629 - INFO - 127.0.0.1 - - [02/Oct/2024 08:16:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-10-02 08:17:30,103 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-02 08:17:30,103 - INFO - [33mPress CTRL+C to quit[0m
2024-10-02 08:17:30,109 - INFO -  * Restarting with stat
2024-10-02 08:17:30,437 - WARNING -  * Debugger is active!
2024-10-02 08:17:30,440 - INFO -  * Debugger PIN: 959-214-118
2024-10-03 16:26:19,956 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-03 16:26:19,956 - INFO - [33mPress CTRL+C to quit[0m
2024-10-03 16:26:24,490 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:24] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:26:24,496 - ERROR - File not found: battleships.txt
2024-10-03 16:26:24,496 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:26:24,501 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:24] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:26:34,524 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:34] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:26:34,526 - ERROR - File not found: battleships.txt
2024-10-03 16:26:34,526 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:26:34,527 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:34] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:26:44,051 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:44] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:26:44,057 - ERROR - File not found: battleships.txt
2024-10-03 16:26:44,057 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:26:44,058 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:44] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:26:46,641 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:46] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:26:46,648 - ERROR - File not found: battleships.txt
2024-10-03 16:26:46,648 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:26:46,649 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:46] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:26:47,696 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:47] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:26:47,700 - ERROR - File not found: battleships.txt
2024-10-03 16:26:47,700 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:26:47,702 - INFO - 127.0.0.1 - - [03/Oct/2024 16:26:47] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:32:13,966 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-03 16:32:13,967 - INFO - [33mPress CTRL+C to quit[0m
2024-10-03 16:32:19,222 - ERROR - File not found: battleships.txt
2024-10-03 16:32:19,222 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:32:19,224 - INFO - 127.0.0.1 - - [03/Oct/2024 16:32:19] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:32:26,088 - INFO - 127.0.0.1 - - [03/Oct/2024 16:32:26] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:32:26,095 - ERROR - File not found: battleships.txt
2024-10-03 16:32:26,095 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:32:26,097 - INFO - 127.0.0.1 - - [03/Oct/2024 16:32:26] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:32:26,418 - INFO - 127.0.0.1 - - [03/Oct/2024 16:32:26] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:32:26,423 - ERROR - File not found: battleships.txt
2024-10-03 16:32:26,423 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:32:26,425 - INFO - 127.0.0.1 - - [03/Oct/2024 16:32:26] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 16:43:19,800 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-03 16:43:19,801 - INFO - [33mPress CTRL+C to quit[0m
2024-10-03 16:43:35,811 - INFO - 127.0.0.1 - - [03/Oct/2024 16:43:35] "[32mGET / HTTP/1.1[0m" 302 -
2024-10-03 16:43:35,816 - ERROR - File not found: battleships.txt
2024-10-03 16:43:35,817 - ERROR - Exception on /placement [GET]
Traceback (most recent call last):
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 32, in create_battleships
    with open(filename, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'battleships.txt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\app.py", line 21, in placement_interface
    ships = create_battleships()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ollyj\Documents\GitHub\battleships\battleships_game\components.py", line 39, in create_battleships
    raise FileNotFoundError(f"File not found: {filename}") from exc
FileNotFoundError: File not found: battleships.txt
2024-10-03 16:43:35,819 - INFO - 127.0.0.1 - - [03/Oct/2024 16:43:35] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 17:04:03,179 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-10-03 17:04:03,179 - INFO - [33mPress CTRL+C to quit[0m
2024-10-03 17:04:03,186 - INFO -  * Restarting with stat
2024-10-03 17:04:03,521 - WARNING -  * Debugger is active!
2024-10-03 17:04:03,525 - INFO -  * Debugger PIN: 959-214-118
2024-10-03 17:04:07,503 - INFO - 127.0.0.1 - - [03/Oct/2024 17:04:07] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-03 17:04:08,279 - INFO - 127.0.0.1 - - [03/Oct/2024 17:04:08] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-03 17:04:08,422 - INFO - 127.0.0.1 - - [03/Oct/2024 17:04:08] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2024-10-03 17:04:08,443 - INFO - 127.0.0.1 - - [03/Oct/2024 17:04:08] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2024-10-03 17:04:08,491 - INFO - 127.0.0.1 - - [03/Oct/2024 17:04:08] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=lPsrmqLEKNDoO9LsPu6H HTTP/1.1" 200 -
2024-10-03 17:04:08,504 - INFO - 127.0.0.1 - - [03/Oct/2024 17:04:08] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2024-10-03 17:07:33,766 - ERROR - File not found: battleships.txt
2024-10-03 17:07:33,790 - INFO - 127.0.0.1 - - [03/Oct/2024 17:07:33] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 17:07:33,801 - INFO - 127.0.0.1 - - [03/Oct/2024 17:07:33] "GET /placement?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2024-10-03 17:07:33,803 - INFO - 127.0.0.1 - - [03/Oct/2024 17:07:33] "GET /placement?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2024-10-03 17:07:33,813 - INFO - 127.0.0.1 - - [03/Oct/2024 17:07:33] "GET /placement?__debugger__=yes&cmd=resource&f=console.png&s=lPsrmqLEKNDoO9LsPu6H HTTP/1.1" 200 -
2024-10-03 17:07:33,825 - INFO - 127.0.0.1 - - [03/Oct/2024 17:07:33] "GET /placement?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2024-10-03 17:47:19,073 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:19] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-03 17:47:19,336 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:19] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-03 17:47:19,345 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:19] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-10-03 17:47:19,347 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:19] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-10-03 17:47:19,357 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:19] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png&s=lPsrmqLEKNDoO9LsPu6H HTTP/1.1[0m" 304 -
2024-10-03 17:47:19,365 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:19] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-10-03 17:47:23,774 - ERROR - File not found: battleships.txt
2024-10-03 17:47:23,788 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:23] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 17:47:23,798 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:23] "[36mGET /placement?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-10-03 17:47:23,798 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:23] "[36mGET /placement?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-10-03 17:47:23,807 - INFO - 127.0.0.1 - - [03/Oct/2024 17:47:23] "[36mGET /placement?__debugger__=yes&cmd=resource&f=console.png&s=lPsrmqLEKNDoO9LsPu6H HTTP/1.1[0m" 304 -
2024-10-03 17:49:00,497 - INFO -  * Detected change in 'C:\\Users\\ollyj\\Documents\\GitHub\\battleships\\battleships_game\\components.py', reloading
2024-10-03 17:49:00,568 - INFO -  * Restarting with stat
2024-10-03 17:49:00,926 - WARNING -  * Debugger is active!
2024-10-03 17:49:00,929 - INFO -  * Debugger PIN: 959-214-118
2024-10-03 17:49:25,331 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-03 17:49:26,333 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:26] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-10-03 17:49:26,440 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:26] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-10-03 17:49:26,455 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:26] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-10-03 17:49:26,495 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:26] "GET /?__debugger__=yes&cmd=resource&f=console.png&s=2UhYDZ581T2ffaDDBPno HTTP/1.1" 200 -
2024-10-03 17:49:26,503 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:26] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2024-10-03 17:49:30,346 - ERROR - File not found: ./battleships.txt
2024-10-03 17:49:30,362 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:30] "[35m[1mGET /placement HTTP/1.1[0m" 500 -
2024-10-03 17:49:30,372 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:30] "[36mGET /placement?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2024-10-03 17:49:30,373 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:30] "[36mGET /placement?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2024-10-03 17:49:30,385 - INFO - 127.0.0.1 - - [03/Oct/2024 17:49:30] "GET /placement?__debugger__=yes&cmd=resource&f=console.png&s=2UhYDZ581T2ffaDDBPno HTTP/1.1" 200 -
2024-10-03 17:49:42,057 - INFO -  * Detected change in 'C:\\Users\\ollyj\\Documents\\GitHub\\battleships\\battleships_game\\components.py', reloading
2024-10-03 17:49:42,096 - INFO -  * Restarting with stat
2024-10-03 17:49:42,385 - WARNING -  * Debugger is active!
2024-10-03 17:49:42,388 - INFO -  * Debugger PIN: 959-214-118
